# Generated by Django 5.2.4 on 2025-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MRI', 'MRI'), ('X-ray', 'X-ray')], max_length=10)),
                ('region', models.CharField(choices=[('Head', 'Head'), ('Chest', 'Chest'), ('Abdomen', 'Abdomen'), ('Spine', 'Spine'), ('Pelvis', 'Pelvis')], max_length=20)),
                ('image', models.ImageField(upload_to='atlas/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
