# Generated by Django 5.2.4 on 2025-07-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='atlas_series/')),
                ('instance_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AtlasSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modality', models.CharField(choices=[('CT', 'CT'), ('MRI', 'MRI'), ('X-ray', 'X-ray')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('legend_image', models.ImageField(blank=True, null=True, upload_to='atlas_legends/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnatomyImage',
        ),
        migrations.AddField(
            model_name='atlasimage',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='atlas.atlasseries'),
        ),
    ]
