# Generated by Django 5.2.4 on 2025-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Lecture', 'Lecture'), ('Presentation', 'Presentation')], max_length=20)),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('material', models.FileField(blank=True, null=True, upload_to='courses/presentations/')),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('recorded_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
